/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppRouteImport } from './routes/_app.app'
import { Route as AppAppIndexRouteImport } from './routes/_app.app.index'
import { Route as AppAppProfileRouteImport } from './routes/_app.app.profile'
import { Route as AppAppEventEventIdRouteImport } from './routes/_app.app.event.$eventId'
import { Route as AppAppEventEventIdBreakRouteImport } from './routes/_app.app.event.$eventId.break'
import { Route as AppAppEventEventIdBreakRoomIdRouteImport } from './routes/_app.app.event.$eventId.break.$roomId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppProfileRoute = AppAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppEventEventIdRoute = AppAppEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppEventEventIdBreakRoute = AppAppEventEventIdBreakRouteImport.update({
  id: '/break',
  path: '/break',
  getParentRoute: () => AppAppEventEventIdRoute,
} as any)
const AppAppEventEventIdBreakRoomIdRoute =
  AppAppEventEventIdBreakRoomIdRouteImport.update({
    id: '/$roomId',
    path: '/$roomId',
    getParentRoute: () => AppAppEventEventIdBreakRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app': typeof AppAppRouteWithChildren
  '/app/profile': typeof AppAppProfileRoute
  '/app/': typeof AppAppIndexRoute
  '/app/event/$eventId': typeof AppAppEventEventIdRouteWithChildren
  '/app/event/$eventId/break': typeof AppAppEventEventIdBreakRouteWithChildren
  '/app/event/$eventId/break/$roomId': typeof AppAppEventEventIdBreakRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/profile': typeof AppAppProfileRoute
  '/app': typeof AppAppIndexRoute
  '/app/event/$eventId': typeof AppAppEventEventIdRouteWithChildren
  '/app/event/$eventId/break': typeof AppAppEventEventIdBreakRouteWithChildren
  '/app/event/$eventId/break/$roomId': typeof AppAppEventEventIdBreakRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/app': typeof AppAppRouteWithChildren
  '/_app/app/profile': typeof AppAppProfileRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/event/$eventId': typeof AppAppEventEventIdRouteWithChildren
  '/_app/app/event/$eventId/break': typeof AppAppEventEventIdBreakRouteWithChildren
  '/_app/app/event/$eventId/break/$roomId': typeof AppAppEventEventIdBreakRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/app'
    | '/app/profile'
    | '/app/'
    | '/app/event/$eventId'
    | '/app/event/$eventId/break'
    | '/app/event/$eventId/break/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/app/profile'
    | '/app'
    | '/app/event/$eventId'
    | '/app/event/$eventId/break'
    | '/app/event/$eventId/break/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/app'
    | '/_app/app/profile'
    | '/_app/app/'
    | '/_app/app/event/$eventId'
    | '/_app/app/event/$eventId/break'
    | '/_app/app/event/$eventId/break/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/profile': {
      id: '/_app/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppAppProfileRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/event/$eventId': {
      id: '/_app/app/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/app/event/$eventId'
      preLoaderRoute: typeof AppAppEventEventIdRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/app/event/$eventId/break': {
      id: '/_app/app/event/$eventId/break'
      path: '/break'
      fullPath: '/app/event/$eventId/break'
      preLoaderRoute: typeof AppAppEventEventIdBreakRouteImport
      parentRoute: typeof AppAppEventEventIdRoute
    }
    '/_app/app/event/$eventId/break/$roomId': {
      id: '/_app/app/event/$eventId/break/$roomId'
      path: '/$roomId'
      fullPath: '/app/event/$eventId/break/$roomId'
      preLoaderRoute: typeof AppAppEventEventIdBreakRoomIdRouteImport
      parentRoute: typeof AppAppEventEventIdBreakRoute
    }
  }
}

interface AppAppEventEventIdBreakRouteChildren {
  AppAppEventEventIdBreakRoomIdRoute: typeof AppAppEventEventIdBreakRoomIdRoute
}

const AppAppEventEventIdBreakRouteChildren: AppAppEventEventIdBreakRouteChildren =
  {
    AppAppEventEventIdBreakRoomIdRoute: AppAppEventEventIdBreakRoomIdRoute,
  }

const AppAppEventEventIdBreakRouteWithChildren =
  AppAppEventEventIdBreakRoute._addFileChildren(
    AppAppEventEventIdBreakRouteChildren,
  )

interface AppAppEventEventIdRouteChildren {
  AppAppEventEventIdBreakRoute: typeof AppAppEventEventIdBreakRouteWithChildren
}

const AppAppEventEventIdRouteChildren: AppAppEventEventIdRouteChildren = {
  AppAppEventEventIdBreakRoute: AppAppEventEventIdBreakRouteWithChildren,
}

const AppAppEventEventIdRouteWithChildren =
  AppAppEventEventIdRoute._addFileChildren(AppAppEventEventIdRouteChildren)

interface AppAppRouteChildren {
  AppAppProfileRoute: typeof AppAppProfileRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppEventEventIdRoute: typeof AppAppEventEventIdRouteWithChildren
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppProfileRoute: AppAppProfileRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppEventEventIdRoute: AppAppEventEventIdRouteWithChildren,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
